chaospace:
  # Blog Information
  title:        "Chaospace"
  subtitle:     "Modern Jekyll based blog for chaospace"
  cover_image:  blog-cover.jpg
  logo:         logo.png
  
  # Company information
  company:      chaospace
  url:          http://chaospace.github.io
  facebook:     chaospace
  twitter:      ichaospace
  gplus:        '101183822199340201470'
  about_link:   http://chaospace.github.io/timeline
  
  # Product Information
  projects_link: http://chaospace.github.io/projects
  #tagline:      ""
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname: 'chasopaceblog'
  
  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false
    
  
 # Analytics     
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html
      
      
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url : http://chaospace.github.io

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter: pygments
#highlighter: rouge
relative_permalinks: true

permalink:     pretty
paginate_path: 'page:num'
paginate: 10

markdown:      kramdown

excerpt_separator: "<!-- more -->"

safe: true
baseurl:     
lsi:         false

redcloth:
 hard_breaks: true
